{{- if not .Values.parser.serviceAccount.skipRoleBinding -}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubevious-parser.fullname" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
{{- end }}