{{- if .Values.backend.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubevious-backend.serviceAccountName" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-backend.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
  {{- with .Values.backend.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
