---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevious-parser.fullname" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
      {{- include "kubevious.match-labels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.parser.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
        {{- include "kubevious.labels" . | nindent 8 }}
    spec:
      {{- with .Values.parser.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubevious-parser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.parser.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.parser.securityContext | nindent 12 }}
          image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag }}"
          imagePullPolicy: {{ .Values.parser.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: LOG_LEVEL
              value: "{{ .Values.parser.log.level }}"
            - name: KUBEVIOUS_COLLECTOR
              value: "{{ include "kubevious-collector.baseUrl" . }}/api/v1/collect"
            - name: SERVER_PORT
              value: "4003"
{{- if .Values.parser.v8MaxOldSpace }}
            - name: NODE_OPTIONS
              value: "--max-old-space-size={{ .Values.parser.v8MaxOldSpace }}"
{{- end }}
          envFrom:  
            - configMapRef:
                name: {{ include "kubevious-worldvious.config" . }}
            - secretRef:
                name: {{ include "kubevious-worldvious.secret" . }}
          ports:
            - name: http
              containerPort: 4003
              protocol: TCP
          resources:
            {{- toYaml .Values.parser.resources | nindent 12 }}
      {{- with .Values.parser.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parser.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parser.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
