apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubevious-parser.fullname" . }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.parser.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
      {{- include "kubevious.labels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.parser.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        app.kubernetes.io/component: {{ include "kubevious-parser.fullname" . }}
        {{- include "kubevious.labels" . | nindent 8 }}
    spec:
      {{- with .Values.parser.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubevious-parser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.parser.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.parser.securityContext | nindent 12 }}
          image: "{{ .Values.parser.image.repository }}:{{ .Values.parser.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.parser.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: "production"
            - name: KUBEVIOUS_COLLECTOR
              value: {{ include "kubevious.collector" . }}
          ports:
            - name: http
              containerPort: 4002
              protocol: TCP
          resources:
            {{- toYaml .Values.parser.resources | nindent 12 }}
      {{- with .Values.parser.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parser.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.parser.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
