apiVersion: kubevious.io/v1
kind: ValidationState
metadata:
  name: change-53f7a0a4-53e5-4e58-bdf1-f5efa12db6c2
  namespace: default
status:
  state: Running
  success: true
  summary:
    issues: 
      raised:
        errors: 100
        warnings: 200
      cleared:
        errors: 100
        warnings: 200
  issues:
    - dn: a/b/c/d
      msg: Service account heapster is not found.
      severity: error