apiVersion: v1
kind: Pod
metadata:
  name: kubevious-mysql-credentials-setup
  namespace: kubevious
spec:
  restartPolicy: Never
  containers:
  - name: mysql
    image: "mysql:8.0.19" #bash #
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
    env:
    - name: MYSQL_HOST
      value: kubevious-mysql
    - name: MYSQL_DATABASE
      value: "test"
    - name: MYSQL_USER
      value: "kubevious"
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubevious-mysql-secret
          key: MYSQL_PASS
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: kubevious-mysql-secret-root
          key: MYSQL_ROOT_PASSWORD
    command:
    - bash
    - "-c"
    - |
      set -ex
      echo "Setting up credentials on Kubevious MySQL DB..."
      echo "Assuming legacy Kubevious deployment with no root password."
      echo "Host: ${MYSQL_HOST}"
      env | grep MYSQL
      mysql --host=$MYSQL_HOST --user=root --password= << EOF
      show databases;
      GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'localhost';
      ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
      FLUSH PRIVILEGES;
      EOF