apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: validationstates.kubevious.io
spec:
  group: kubevious.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              properties:
                state:
                  type: string
                date:
                  type: string
                  format: datetime
                success:
                  type: boolean
                summary:
                  type: object
                  properties:
                    issues:
                      type: object
                      properties:
                        raised:
                          type: object
                          properties:
                            errors: 
                              type: number
                            warnings: 
                              type: number
                          required:
                            - errors
                            - warnings
                        cleared:
                          type: object
                          properties:
                            errors: 
                              type: number
                            warnings: 
                              type: number
                          required:
                            - errors
                            - warnings
                      required:
                        - raised
                        - cleared
                  required:
                    - issues
                raisedIssues:
                  type: array
                  items:
                    type: object
                    properties:
                      dn:
                        type: string
                      msg:
                        type: string
                      severity:
                        type: string
                    required:
                      - dn
                      - msg
                      - severity
                clearedIssues:
                  type: array
                  items:
                    type: object
                    properties:
                      dn:
                        type: string
                      msg:
                        type: string
                      severity:
                        type: string
                    required:
                      - dn
                      - msg
                      - severity                      
              required:
                - state
                - date
          required:
            - status
  scope: Namespaced
  names:
    plural: validationstates
    singular: validationstate
    kind: ValidationState