apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: changepackages.kubevious.io
spec:
  group: kubevious.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            data:
              type: object
              properties:
                charts:
                  type: array
                  items:
                    type: object
                    properties:
                      namespace:
                        type: string
                      name:
                        type: string
                    required:
                      - namespace
                      - name
                changes:
                  type: array
                  items:
                    type: object
                    properties:
                      data:
                        type: string
                    required:
                      - data
                deletions:
                  type: array
                  items:
                    type: object
                    properties:
                      apiVersion:
                        type: string
                      kind:
                        type: string
                      namespace:
                        type: string
                      name:
                        type: string
                    required:
                      - apiVersion
                      - kind
                      - name
          required:
            - data
  scope: Namespaced
  names:
    plural: changepackages
    singular: changepackage
    kind: ChangePackage