apiVersion: v2
name: kubevious-agent
description: A Helm chart for Kubevious Agent
type: application
keywords:
  - kubernetes ui
  - kubernetes web ui
  - kubernetes configuration checker
  - kubernetes validator
icon: https://kubevious.io/img/logo.png
version: 0.9.17
appVersion: 0.9.17
