apiVersion: v2
name: kubevious-agent
description: A Helm chart for Kubevious SaaS Agent
type: application
keywords:
  - kubernetes ui
  - kubernetes web ui
  - kubernetes configuration checker
  - kubernetes validator
icon: https://kubevious.io/img/logo.png
version: 1.0.3
appVersion: 1.0.3
