---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevious-worldvious.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: {{ include "kubevious-worldvious.fullname" . }}
    {{- include "kubevious.labels" . | nindent 4 }}
type: Opaque
data:
  WORLDVIOUS_ID: {{ include "kubevious-worldvious.id" . | quote }}
